server:
  port: 8888

spring:
  application:
    name: CONFIG-SERVICE

  cloud:
    config:
      server:
        git:
          uri: https://github.com/yogeshmungase/ai-detection-config-repo
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"